import time
delay = 1
x = 0

# Hello Reader! V15

def wizard_ascii(): 
    print(f"                                           ____")
    print(f"                                          '###' ")
    print(f"                                         /'##(  ")
    print(f"                                      __/_#_#(_  ")
    print(f"                                     / _______ \  ")
    print(f"                                    _\_)/___\(_/_   ")
    print(f"                                   / _((\- -/))_ \  ")
    print(f"                                   \ \())(-)(()/ /  ")
    print(f"                                    ' \(((()))/ '   ")
    print(f"                                   / ' \)).))/ ' \  ")
    print(f"                                  / _ \ - | - /_, \  ")
    print(f"                                 (   ( .;''';. .   ) ")
    print(f"                                 _\'__ /    )\ __'/_  ")
    print(f"                                   \/  \   ' /  \/   ")
    print(f"                                    .'  '...' ' )  ")
    print(f"                                      / / | \ \       ")
    print(f"                                     / .  .  . \    ")
    print(f"                                    /   .   .   \    ")
    print(f"                                   /   /  |  \   \    ")
    print(f"                                  '   /   b   '   '   ")
    print(f"                                 '   /    Bb   '   '   ")
    print(f"                               _'   |     BBb   '_  '_    ")
    print(f"                            _'      |     BBBb   '_    '_    ")
    print(f"                         (-'______JH\____.BDBBb.____)_____)      ")

def ghost_art():
    print(f"                                     .--,      ")
    print(f"                                    /  (           ")
    print(f"                                   /    \          ")
    print(f"                                  /      \         ")
    print(f"                                 /  0  0  \        ")
    print(f"                          ((()  |    ()    |   ()))    ")
    print(f"                          \  () (  .____.  )  ()  /   ")
    print(f"                          |`  \_/\  `==`  / \_/  `|      ")
    print(f"                          |       `.'--'.`        |    ")
    print(f"                           \        `==`          |    ")
    print(f"                            \                    /      ")
    print(f"                             `.                .'    _''  ")
    print(f"                              |`               |_'--'  |  ")
    print(f"                              |                       /     ")
    print(f"                              \                     .'         ")
    print(f"                               `.________________.-'    "       )

def towergame():

    global x
            
    print('\n')
    time.sleep(delay)
    print( 'Welcome to "THE TOWER: A Text-Based RPG!"')
    print('')
    time.sleep(delay)
    print('Beware! This is a game of choices, and the consequences will be severe!')
    time.sleep(delay)
    print('With each mistake you may make, learn and adapt to work towards beating THE TOWER!')
    time.sleep(delay)
    print('')

    def namecheck():

        global x

        global name

        print( 'Before you can begin on your adventure through THE TOWER, please input the name of your character:')
        print('')
        time.sleep(delay)
        name = input( '< ')
        x = len(name)
        if x == 0:
            print('')
            print ("Invalid name, at least one character needed. Please try again.")
            print('')
        else:
            pass
    while x == 0:
        namecheck()

    print('')
    time.sleep(delay)
    print( 'Welcome to world of Temaria', name + '!')
    time.sleep(delay)
    print(f'Now, what race would you like your character to be?')
    print('')
    time.sleep(delay)
    print( '1: Human' '\n' '2: Dwarf' '\n' '3: Elf' '\n' '4: Half-Orc')
    print('')
    while True:
        race_num = input( '< ')
        if race_num == '1':
            race = 'Human'
            break
        if race_num == '2':
            race = 'Dwarf'
            break
        if race_num == '3':
            race = 'Elf'
            break
        if race_num == '4':
            race = 'Half-Orc'
            break
        print('')
        print('Invalid response, please enter the number of the race you wish to select!')
        print('')

    print('')
    time.sleep(delay)
    print( f'So you wish to begin your story as {name} the {race}?')
    time.sleep(delay)
    print('So it shall be! But before you proceed... I wish you good luck adventurer - may you make the right choices throughout...')

    print('')
    time.sleep(delay)
    input( 'Continue < ')

    print('')
    time.sleep(delay)
    print('This wicked yet magical story begins with you, our hero of this story...')
    print('')
    time.sleep(delay)
    print(f'You are Knight {name}! Known far and wide, to the edge of Temaria and back, as the {race} champion hailing from the Kingdom of Nevaros.')
    print('Your past deeds and actions proceed you, namely, the slaying of the feared storm-dragon Glavigorn by your blade.')
    time.sleep(delay)
    print('Despite the odds always being against you, time and time again, you have saved the Kingdom of Nevaros from countless threats.')
    print(f'Even the sheer thought of the name {name} strikes aspiration into the hearts and minds of many folk.')

    print('')
    time.sleep(delay)
    input( 'Continue < ')

    print('')
    time.sleep(delay)
    print('The Kingdom of Nevaros is made up of peaceful lands, and is known as a beacon of pure hope to the whole world of Temaria.')
    time.sleep(delay)
    print('From its vast valleys, to the dense forests, Nevaros is the largest province in the land.')
    print('')
    time.sleep(delay)
    print('To the north is the dominion of the Frost Giants, the second largest territory. They are quite the barbaric tribe, known to rule with an iron fist.')
    time.sleep(delay)
    print('Their homeland is inhospitable and cold. The icy caves and frozen lakes do not help with farming. Hence, they are known to raid other nations.')
    print('')
    time.sleep(delay)
    print('To the much warmer south exists the Elven Empire, the third largest major kingdom. The elven people are peaceful yet mysterious. Outsiders know not much of their kind.')
    time.sleep(delay)
    print('Yet, their lands are beautiful and rich - often bathed in the southern golden light.')

    print('')
    time.sleep(delay)
    input( 'Continue < ')
    print('')
    time.sleep(delay)
    print('Nonetheless, let us continue with our little story...')
    time.sleep(delay)
    print('One fateful day, you arrive (much later than expected) at your post within the Kings Keep like usual.')
    time.sleep(delay)
    print('But instead of lively room of conversation, you are met with a seemingly completely deserted room...')
    print('')
    time.sleep(delay)
    print("'Knight!' The King cries, running towards you.")
    print(f"'{name}! Where have you been? We have been looking for you all morning!' He exclaims, 'We have had reports of an evil sorcerer using foul magics within Nevaros!'")

    print('')
    time.sleep(delay)
    input( 'Continue < ')
    print('')

    time.sleep(delay)
    print("'His name is Damazo Zanthar! He has captured the old watchtower just outside the city. He has begun to use his wicked magics upon our very citizens!'")
    time.sleep(delay)
    print("'We could not let this stand... So we had sent your fellow Knight Ralph to investigate in your absence earlier this morn.'")
    time.sleep(delay)
    print("'Yet since he has left we have heard nought back and fear for the worst. You must venture out and rescue him!'")
    print('')
    time.sleep(delay)
    print("'...But beware, humble Knight, as this is no ordinary wizard. He will use his immense mastery of the arcane and trickery to foil all of your plans!'")
    time.sleep(delay)
    print(f"'So you must be careful! We have readied your horse in the meanwhile. Please, {name} go and save Ralph!'")
    print('')
    time.sleep(delay)
    print('You nod, valiantly, before rushing out of the kings keep and down to the stables where you hop upon your noble steed.')

    print('')
    time.sleep(delay)
    input( 'Continue < ')
    print('')

    time.sleep(delay)
    print('After half a day of riding, you find youself at the foot of a very tall, winding tower.')
    time.sleep(delay)
    print('The entire form of which had been twisted and distorted by the foul magics mentioned prior.')
    print('')
    time.sleep(delay)
    print('You feel an overwhelming sense of dread, yet dismount your steed and tie it to a post nearby.')
    print('')
    time.sleep(delay)
    print('You offer a brief farewell to your horse, hopefully not for the last time, before climbing the cobbled steps towards the towers main entrance.')
    time.sleep(delay)
    print('A large wooden door bars your entry, you break it open easily with a BASH from your iron gauntlet. You take a deep breath.')
    print('')
    time.sleep(delay)
    print('You step inside...')

    print('')
    time.sleep(delay)
    input('Continue < ')

    riddleroom()

def riddleroom():
    room = 'riddleroom'

    print('')
    time.sleep(delay)
    print( "You enter a dark room with four walls, it’s almost entirely silent except for the howl of the wind.")
    time.sleep(delay)
    print('You see the wind is coming from an open window in front of you, it gently blows through the tattered curtains.')
    time.sleep(delay)
    print("You shiver, and acknowledge how cold it is.")
    print(" ")
    time.sleep(delay)
    print("You see two doors. One on the left wall, one on the right.")
    time.sleep(delay)
    print("Both are huge, ornate doors with brass hinges and handles. The door on the left has a ruby, the door on the right has a pearl.")
    print(" ")
    time.sleep(delay)
    print("There is a plinth in the middle of the room. It’s made of dark wood. It looks old and weathered.")
    time.sleep(delay)
    print("You see that there is text engraved upon it. It reads as the following:")
    print(" ")
    time.sleep(delay)
    print("'Lovely and round, I shine with pale light; grown in the darkness, a lady's delight. What am I?'")
    print("")
    time.sleep(delay)
    print("You realise the answer must be Ruby or Pearl, since the doors you saw had those gems inserted in them.")
    print("")
    time.sleep(delay)
    print('But what is the answer?')

    print("")
    time.sleep(delay)
    decision = input( '< ')

    if room.lower() == "riddleroom" and decision.lower() == "pearl":
        time.sleep(delay)
        print("")
        print("You enter through the pearl door, taking you into the wine cellar...")
        wine_cellar()
    elif room.lower() == "riddleroom" and decision.lower() == "ruby":
        time.sleep(delay)
        print("")
        time.sleep(delay)
        print("You enter through the ruby door, taking you into the dungeons...")
        dungeonroom()
    else:
        print("")
        print("Invalid input, now retry from the start of the room.")
        print("")
        riddleroom()

def wine_cellar():
    room = "wine cellar"

    print("")
    time.sleep(delay)
    print( "You find yourselsf in a damp, old wine cellar. Within the cellar are multiple shelves housing flasks of various liquids.") 
    time.sleep(delay)
    print("Some contain thick, seemingly poisonous fluid with visible insects crawling within.")
    time.sleep(delay)
    print("")
    print(f'Suddenly, a ghastly yet reassuring voice quietly whispers to you. "Be courageous {name}! Drink the red one! Top shelf!"')
    time.sleep(delay)
    print('"It is the potion of strength and force!"')
    time.sleep(delay)
    print("")
    print("You see the mentioned bottle, but you need to exert yourself to reach it.")
    time.sleep(delay)
    print('Before you can even decide on what to do, lots of magically corrupted pythons slither in through a crack in the wall!')
    time.sleep(delay)
    print('They notice you, and immediately start to rush towards you!')
    time.sleep(delay)
    print("")
    print("Do you try reach for the red potion before the pythons can reach you? Yes or No?")

    print("")
    time.sleep(delay)
    decision = input('< ')

    if room.lower() == "wine cellar" and decision.lower() == "yes":
        print("")
        time.sleep(delay)
        print( 'You reach and just about get the potion!')
        time.sleep(delay)
        print('You jump over the pythons and rush to the door on the far side - quickly opening it and going through.')
        print("")
        time.sleep(delay)
        print("You practically fly through the door you just opened, and enter the haunted ballroom...")
        print("")
        ballroom()
    elif room.lower() == "wine cellar" and decision.lower() == "no":
        time.sleep(delay)
        print("")
        time.sleep(delay)
        print( "You are now dinner for the pythons!")
        time.sleep(delay)
        print("They begin to bite you, before working as a team to devour you whole...")
        print("")
        print('You are now dead. Retry the room.')
        wine_cellar()
    else:
        print('')
        print("Invalid input, now retry from the start of the room.")
        print("")
        wine_cellar()

def dungeonroom():
    room = 'dungeon'

    print('')
    time.sleep(delay)
    print( 'You enter a dungeon, the smell of decaying bodies hits your nostrils. You then avert your eyes to the ground, to which you see seemingly thousands upon thousands of plagued, deathly rats.')
    time.sleep(delay)
    print("Before you can even react, the rats begin to swarm you, clawing at your clothes. You are desperate to get the rats off from you.")
    time.sleep(delay)
    print("You start to stamp, pawing at your clothes, desperate to get the rats off you.")
    print('')
    time.sleep(delay)
    print('You cannot seem to reach for your own sword with the rats blocking it...')
    time.sleep(delay)
    print("Just a few seconds before the rats can completely swamp you, something glints out the corner of your eye...")
    print('')
    time.sleep(delay)
    print("You see a long broadsword! It is adorned with a golden handle, rubies inlaid.")
    time.sleep(delay)
    print('')
    print("Do you attempt to grasp out, aiming to pick it up? Yes or No?")

    print('')
    time.sleep(delay)
    dungeonchoice = input('< ')

    if(dungeonchoice.lower() == "yes"):
            print('')
            time.sleep(delay)
            print( "You pick up the sword, it's heavy.")
            time.sleep(delay)
            print("Do you cleave forward at the rats? Yes or No?")
            print('')
            slashratschoice = input( "> ")
            time.sleep(delay)
            if(slashratschoice.lower() == "yes"):
                print('')
                time.sleep(delay)
                print( "You swing the sword wildly, cutting rats left and right, slicing through them like a knife through butter.")
                time.sleep(delay)
                print("The whole ordeal is brutal, but better them than you, you think to yourself.")
                time.sleep(delay)
                print("It’s finally over. Silence then echoes through the dungeon. In one of the cells you see a rusted old key.")
                print('Do you pick it up? Yes or No?')
                print('')
                time.sleep(delay)
                dungeonkeychoice = input( "> ")
                if(dungeonkeychoice.lower()) == "yes":
                    print('')
                    time.sleep(delay)
                    print( "You take the key to the door on the far side of the room.")
                    time.sleep(delay)
                    print("The key fits into the lock, and the door swings open with ease.")
                    time.sleep(delay)
                    print('You make your way to the library...')
                    library()
                elif(dungeonkeychoice.lower()) == "no":
                    print('')
                    time.sleep(delay)
                    print( "You leave the key behind. But as you turn your back to it; they key transforms into a malformed, eldritch being.")
                    time.sleep(delay)
                    print('')
                    print('It swiftly approaches you and kills you.')
                    time.sleep(delay)
                    print('')
                    print('You are now dead. Retry the room.')
                    time.sleep(delay)
                    dungeonroom()
                else:
                    print('')
                    time.sleep(delay)
                    print("Invalid input, now retry from the start of the room.")
                    time.sleep(delay)
                    dungeonroom()
            elif(slashratschoice.lower()) == "no":
                print('')
                time.sleep(delay)
                print( "The rats start to claw through your clothes and then into your skin. It is incredibly painful, you try to throw the rats off, but to no avail - they keep coming back.")
                time.sleep(delay)
                print("You realise your time is nearly up.")
                time.sleep(delay)
                print('')
                print('You are now dead. Retry the room.')
                time.sleep(delay)
                dungeonroom()
            else:
                print('')
                print("Invalid input, now retry from the start of the room.")
                dungeonroom()
    elif(dungeonchoice.lower()) == "no":
        print('')
        time.sleep(delay)
        print( "The rats start to claw through your clothes and then into your skin. It is incredibly painful, you try to throw the rats off, but to no avail - they keep coming back.")
        time.sleep(delay)
        print("You realise your time is nearly up...")
        time.sleep(delay)
        print('')
        print('You are now dead. Retry the room.')
        time.sleep(delay)
        dungeonroom()
    else:
        print('')
        print("Invalid input, now retry from the start of the room.")
        dungeonroom()

def library():
    room = 'library'
    print('')
    time.sleep(delay)
    print('The next room contains utter darkness. You are unable to make out anything within the room, yet you step inside.')
    time.sleep(delay)
    print('Suddenly, a burst of light erupts from previously unlit candles.')
    time.sleep(delay)
    print('The lights reveal this room to be a forgotten library; filled with books misplaced. The shelves that once stood now lay damaged on the floor.')

    print('')
    time.sleep(delay)
    print('As you walk further in, you notice a floating object suspended in the air in the center of the room.')
    time.sleep(delay)
    print('The object is revealed to you as being as a book! It is crafted from some sort of flesh from a demonic creature.')
    time.sleep(delay)
    print('Before you can get close, magic explodes from the book causing it to shine bright purple.')

    print('')
    time.sleep(delay)
    input('Continue < ')

    print('')
    time.sleep(delay)
    print('The book seemingly comes to life, and flies into your hands before you can react. You can decipher the book has the nature of a trickster.')
    time.sleep(delay)
    print('It then begins to speak.')

    print('')
    time.sleep(delay)
    print(f'Answer my riddle wisely {name}, you have done well so far!')
    time.sleep(delay)
    print('With the correct answer, you will go to a room with splendour...')
    time.sleep(delay)
    print('But with an incorrect answer, you will go to a room of despair...')
    time.sleep(delay)
    print('The book laughs to itself, you dont find it very funny.')
    
    print('')
    time.sleep(delay)
    print('The riddle is:')
    time.sleep(delay)
    print('What is so fragile, that saying its very name breaks it?')
    time.sleep(delay)
    print("[1] Glass. [2] Fire. [3] Silence. [4] Brick.")

    print('')
    decision = input('< ')

    if room.lower() == "library" and decision.lower() == "1":
        print('')
        time.sleep(delay)
        print('Wrong! You now go to the ballroom...')
        time.sleep(delay)
        print('The book opens a previously hidden passage to your left. You go through.')
        ballroom()
    elif room.lower() == "library" and decision.lower() == "2":
        print('')
        time.sleep(delay)
        print('Wrong! You now go to the ballroom...')
        time.sleep(delay)
        print('The book opens a previously hidden passage to your left. You go through.')
        ballroom()
    elif room.lower() == "library" and decision.lower() == "3":
        print('')
        time.sleep(delay)
        print(f"Correct! To the Armoury you go {name}.")
        time.sleep(delay)
        print('The book opens a previously hidden passage to your right. You go through.')
        armoury()
    elif room.lower() == "library" and decision.lower() == "4":
        print('')
        time.sleep(delay)
        print('Wrong! You now go to the ballroom...')
        time.sleep(delay)
        print('The book opens a previously hidden passage to your left. You go through.')
        ballroom()
    else:
        print('')
        print("Invalid input, now retry from the start of the room.")
        library()

def ballroom():
    room = ballroom
    time.sleep(delay)
    print( "A crowd of ghastly ghosts shimmer within the ballroom, appearing in front of you. One ancient yet corrupted knight stands in the center of the room!")
    print('')

    ghost_art()

    print('')
    time.sleep(delay)
    input('Continue < ')
    print('')

    time.sleep(delay)
    print("[1] Do you confront your fears and face the Knight?\n[2] You're too afraid of the situation and you choose to run to the next set of doors.")
    print('')

    decision = input('< ')

    if decision == '1':
        print('')
        time.sleep(delay)
        print("You ready your stance to face the Knight")
        time.sleep(delay)
        print("The Knight moves forward, the sound of words are coming out from beneath his helmet.")
        time.sleep(delay)
        print(f'"You have two choices {name}, fight and die OR answer my riddle."')
        time.sleep(delay)
        print('"If you answer my riddle correctly you may live. If not, well, you can join us for all of eternity! HA HA HA!"')
        print('')
        time.sleep(delay)
        print("[1] Fight. [2] I will answer your riddle.")
        print('')
        choice_two = input('< ')
        if choice_two == '1':
            time.sleep(delay)
            print('')
            time.sleep(delay)
            print("You begin battling the Knight. Your attacks are nigh on useless. The ghost knight reaches for you, impaling you with his hand. This gives you a fatal wound.")
            print('')
            time.sleep(delay)
            print('You are now dead. Retry the room.')
            print('')
            ballroom()   
        elif choice_two == '2':
                print('')
                time.sleep(delay)
                print('"This is my riddle: I build up castles, I tear down mountains, I make some men blind, I help others to see. What am I?"')
                print('')
                time.sleep(delay)
                print("[1] Sun. [2] Sand. [3] Water. [4] Brick. [5] Pearl")
                print('')
                choice_three = input('< ')
                if choice_three == '2':
                    print('')
                    time.sleep(delay)
                    print("A low eerie voice in the air says thank you. All of the ghosts in the room (including the knight) vanish away. A shiny white object glitters on the floor.")
                    time.sleep(delay)
                    print( "A protective magic amulet! This will help protect the user from magic. Useful. You pick it up and place it in your inventory.\nNow heading toward the next door.")
                    wizardbattle()
                elif choice_three =='1':
                    print('')
                    time.sleep(delay)
                    print(f'"Hahaha, welcome to our side {name}!" The ghosts within the room fly over and begin to rip out your soul.')
                    print('')
                    time.sleep(delay)
                    print('You are now dead. Retry the room.')
                    print('')
                    ballroom()  
                elif choice_three =='3':
                    print('')
                    time.sleep(delay)
                    print('A glowing red circle appears underneath the knight. The Knight channels from this circle, creating a beam to shoot at you. He blasts it right at you. You are in absolute agony in both body and soul.')
                    print('')
                    time.sleep(delay)
                    print('You are now dead. Retry the room.')
                    print('')
                    ballroom()  
                elif choice_three =='4':
                    print('')
                    time.sleep(delay)
                    print("All of the ghosts in the room suddenly launch a full scale attack on you! They slash and disembowel you into pieces.")
                    print('')
                    time.sleep(delay)
                    print('You are now dead. Retry the room.')
                    print('')
                    ballroom()  
                elif choice_three =='5':
                    print('')
                    time.sleep(delay)
                    print("The ancient Knight's eyes glow a foul green. He charges forward, casting green fire from his eyes that set you on fire. You are now charcoal and dust.")
                    print('')
                    time.sleep(delay)
                    print('You are now dead. Retry the room.')
                    print('')
                    ballroom()
                else:
                    print("Invalid input, now retry from start of the room.")
                    print('')
                    ballroom()
        else:
            print("Invalid input, now retry from the start of the room.")
            print('')
            ballroom()

    elif decision == '2':
        print('')
        time.sleep(delay)
        print("You begin to run away to the next set of doors. Cowardly. Yet, you are still alive. You will remember this.")
        wizardbattle()
    else:
        print('')
        print("Invalid input, now retry from the start of the room.")
        print('')
        ballroom()

def armoury():
    room = armoury

    print('')
    time.sleep(delay)
    print('You walk into the armoury room.') 
    time.sleep(delay)
    print('There are iron torches in the room. They emit a warm, ethereal glow. You glance around and see rows upon rows of mannequins lining the small room. They wear strange and unique armour, vast and varied.')
    time.sleep(delay)
    print('There are more weapons and equipment then you could possibly imagine - some of which you dont exactly know the purpose of...')
    print('')
    time.sleep(delay)
    print('With further inspection, one set of armour looks heavy as if it is made of solid steel. A standard set for a knight like yourself.')
    time.sleep(delay)
    print('Another set looks ornate, embellished with swirling patterns and symbols. Much more regal, maybe for nobility? ...Not like they would need armour, you think to yourself.')
    time.sleep(delay)
    print('The last one you see looks much more light compared to the others. It looks to be chainmail, and has been polished to a shine. Perhaps an archers set? You can see your very reflection in it!')
    print('')
    time.sleep(delay)
    print('You approach to get a better look at them, yet you sense something to be amiss...')
    time.sleep(delay)
    print('You hear the sound of a loud crack! One mannequin is standing behind you… and THEIR SWORD IS RAISED!')
    time.sleep(delay)
    print('They eerily charge you, swinging their sword down on you.')
    print('')
    time.sleep(delay)
    print('Do you:')
    time.sleep(delay)
    print('Clash your sword against theirs? Yes or No?')
    print('')

    clashchoice = input('< ')

    if(clashchoice.lower() == "yes"):
            print('')
            time.sleep(delay)
            print("You quickly ready your weapon against theirs.")
            time.sleep(delay)
            print("You defend against their slash. Barely. You parried their attack! You then counterattack, swifty desposing of the mannequin. It dies, and turns to a heap of ash on the floor")
            print('')
            time.sleep(delay)
            print('But before you can celebrate, three of the previous suits of armour come to life!')
            time.sleep(delay)
            print('Do you stand your ground? Yes or No?')
            print('')

            standgroundchoice = input("< ")
            time.sleep(delay)
            if(standgroundchoice.lower() == "yes"):
                print('')
                time.sleep(delay)
                print("Your bravery proceeds you!")
                time.sleep(delay)
                print('')
                print("The whole ordeal is tough, but you fight three at the same time! They attempt to get the better of you, yet you persist.")
                time.sleep(delay)
                print('You defend against three of them! They slash and stab towards you to no avail. With one large swing of your sword, you take them all out.')
                print('')
                time.sleep(delay)
                print('You see the mannequins drop to the floor, turning to ash. The armour they wore now laying peacefully on the floor.')
                time.sleep(delay)
                print('You notice the three you fought wore the three sets of armour you spotted before!')
                print('')
                time.sleep(delay)
                print("You understand you will have to swap out your current armour for one of them. Do want to equip one? Yes or No?")
                print('')

                time.sleep(delay)
                armour1 = input('< ')

                if(armour1.lower()) == "yes":
                    print('')
                    time.sleep(delay)
                    print("You go towards the three sets of armour on the floor.")
                    time.sleep(delay)
                    print('Which one do you want to go for?')
                    print('')
                    time.sleep(delay)
                    print("[1] The solid steel one. Nothing fancy, yet better than yours.\n[2] The ornate one, fit for kings. It hardly seems practical though.\n[3] The chainmail, light as a feather.")
                    print('')
                    time.sleep(delay)

                    armour2 = input('< ')
                    if armour2 == '1':
                        time.sleep(delay)
                        print('You choose the solid steel set.')
                        print('')
                        time.sleep(delay)
                        print('As fast as you can, you unequip your current armour.')
                        time.sleep(delay)
                        print('You upgrade to slightly better armour. Congratulations!')
                        print('')
                        time.sleep(delay)
                        print('You proceed onwards to the room of the wizard with your new armour!')
                        wizardbattle()
                    elif armour2 == '2':
                        time.sleep(delay)
                        print('You choose the ornate set.')
                        print('')
                        time.sleep(delay)
                        print('As fast as you can, you unequip your current armour.')
                        time.sleep(delay)
                        print('You don the armour fit for the richest within society. You feel fancy, yet, less safe.')
                        print('')
                        time.sleep(delay)
                        print('You proceed onwards to the room of the wizard with your new armour!')
                        wizardbattle()
                    elif armour2 == '3':
                        time.sleep(delay)
                        print('You choose the chainmail set.')
                        print('')
                        time.sleep(delay)
                        print('As fast as you can, you unequip your current armour.')
                        time.sleep(delay)
                        print('You throw the chainmail onto yourself. You feel as fast as the wind!')
                        print('')
                        time.sleep(delay)
                        print('You proceed onwards to the room of the wizard with your new armour!')
                        wizardbattle()
                    else:
                        print('')
                        time.sleep(delay)
                        print("Invalid input, now retry from the start of the room.")
                        time.sleep(delay)
                        armoury()

                elif(armour1.lower()) == "no":
                    print('')
                    time.sleep(delay)
                    print('You decide not to fuff about with swapping armour. You are on a quest here after all!')
                    print('')
                    time.sleep(delay)
                    print('You race towards the next door, leading to the wizards room...')
                    wizardbattle()
                else:
                    print('')
                    time.sleep(delay)
                    print("Invalid input, now retry from the start of the room.")
                    time.sleep(delay)
                    armoury()
            elif(standgroundchoice.lower()) == "no":
                print('')
                time.sleep(delay)
                print(f"Lacking in moral fibre, you, {name}, don't wish to stand your ground against your aggressors. Very well...")
                time.sleep(delay)
                print('You race towards the next door, leading to the wizards room...')
                wizardbattle()
            else:
                print('')
                print('Invalid input, now retry from the start of the room.')
                armoury()
                
    elif(clashchoice.lower()) == "no":
        time.sleep(delay)
        print('')
        print('You do not try to clash with the enemy. The weapon of this enemy crashes down into you, splitting you into two.')
        print('')
        time.sleep(delay)
        print('You are now dead. Retry the room.')
        time.sleep(delay)
        armoury()
    else:
        print('')
        print('Invalid input, now retry from the start of the room.')
        armoury()

def wizardbattle():

    global decision 

    def fight_options():
       global decision
       time.sleep(delay)
       decision = input("What will you do? ")
       print (" ")

       if decision == "1":
          time.sleep(delay)
          print ("The wizard gestures with his hand. The sword is torn from your grasp, he manipulates it with his magic! He makes your, once trusty, sword to fly briefly around the room.")
          time.sleep(delay)
          print ("In a flash, he then calls your sword to bury itself deep in your chest. Brutal...")
          print (" ")
          time.sleep(delay)
          print ('You are now dead. Retry the room.')
          wizardbattle()

       elif decision == "2":
           time.sleep(delay)
           print ("As soon as you grab the staff, he shakes you off. He conjures a massive lightning bolt and shoots it straight into your chest!")
           print (" ")
           time.sleep(delay)
           print ('You are now dead. Retry the room.')
           wizardbattle()

       elif decision == "3":
           time.sleep(delay)
           print ("You thrust the burning torch at the wizard! At once he is enveloped in a cloud of purple flame.")
           time.sleep(delay)
           print ("Who knew he would keep his metaphorical kryptonite close to him. Right under his nose...")
           print (" ")  
           time.sleep(delay)
           print ("The deep purple flame glows brightly for a few moments before vanishing abruptly, leaving only a heap of ashes and his now burnt up wizard hat on the floor.")
           time.sleep(delay)
           print ("You notice his boots stand forlornly remaining.")
           print (" ")
           time.sleep(delay)
           print('You take a deep breath. Your entire journey so far had lead up to this very moment.')
           print (" ")
           time.sleep(delay)
           print('You are proud.')
           print (" ")
           time.sleep(delay)
           print('You are victorious!')
           print (" ")
           endgame()
         
       else:
           print ("Invalid entry please try again")
           print (" ")   

    def talk_or_fight():
       global decision
       time.sleep(delay)
       decision = input("What will you do? ")
       if decision == "1":
          print (" ")
          time.sleep(delay)
          print ("Go for it! Temaria will be a much better place without him!")
          print (" ")
       elif decision == "2":
          print (" ")
          time.sleep(delay)
          print (f"He laughs. 'Were you born this stupid {name}, or are all Knights of Nevaros THIS dumb? Fight or die!'")
          print (" ")
       else:
          print (" ")
          print ("Invalid entry please try again")
          print (" ")

    print (" ")
    time.sleep(delay)
    print ("You enter a dark chamber well lit by magical torches whose flames burn in strange, powerful colours.")
    time.sleep(delay)
    print ("The air is filled with swirls and pools of scented smoke; the clouds twist into shapes of the faces of people you have known.")
    time.sleep(delay)
    print ("People from within your past quests, your loved ones and even the king.")
    print (" ")
    time.sleep(delay)
    print ("Just for a moment the smoke clears, and on the far side of the chamber you glimpse Ralph standing still")
    time.sleep(delay)
    print ("and silent inside an iron cage. You call out to him! But he shows no signs that he is even aware of your presence.")
    time.sleep(delay)
    print ("The smoke then obscures your view. Cautiously, you start to move towards the cage.")

    print (" ")
    time.sleep(delay)
    input ("Continue > ")
    print (" ")

    wizard_ascii()

    print (" ")
    time.sleep(delay)
    input ("Continue > ")
    print (" ")

    time.sleep(delay)
    print ("Suddenly there is a flash of red light to your left. You turn and see an ancient, stooped man.")
    time.sleep(delay)
    print ("He is dressed in the robes of a High Mage, albeit very corrupted with dark magics.")
    print (" ")
    time.sleep(delay)
    print ("'It is I! Damazo Zanthar!' he says 'Who is this brave soul who trespasses in my lair?' He then leans onto his staff, menacingly looking towards you.")
    time.sleep(delay)
    print (f"He grins unpleasantly, a wicked expression upon his face. 'So, my magics tell me you are {name}! My, what a brave hero! You have come to rescue your friend have you?' He laughs to himself. Excellent!")
    time.sleep(delay)
    print ("Now I shall have TWO souls to steal to renew my youth! Prepare to die!'")

    print (" ")
    time.sleep(delay)
    input ("Continue > ")
    print (" ")

    time.sleep(delay)
    print ("You must decide - do you want to fight the mage or try to reason with him?")
    print (" ")
    time.sleep(delay)
    print ("[1] to fight, or [2] to talk.")
    print (" ")

    decision = " "
    while (decision != "1" and decision != "2"):       
           talk_or_fight()

    time.sleep(delay)
    print ("You charge at the wizard, dodging left and right as he hurls fireballs at you from the tip of his staff.")
    time.sleep(delay)
    print ("As you get closer and closer to him, you must decide what to do.")
    print (" ")
    time.sleep(delay)
    print ("Enter [1] to attack him with your sword!")
    time.sleep(delay)
    print ("Enter [2] to try and grab his staff!")
    time.sleep(delay)
    print ("Enter [3] to grab the nearest torch from the wall to attack him with!")
    print (" ")

    decision = " "
    while (decision != "1" and decision != "2" and decision !="3"):
           fight_options()

def endgame():
    print('')
    time.sleep(delay)
    print('You rush over to the cage containing Ralph. With his life force no longer being drained by Damazo; he already looks to be in much better shape.')
    time.sleep(delay)
    print('The magical force upheld by Damazo to keep the cage locked ceases to exists. The door flails open with a squeak.')
    time.sleep(delay)
    print('Ralph drops to the floor, barely able to stand. You know what you must do.')
    time.sleep(delay)
    print('')
    time.sleep(delay)
    print('You call out to him, asking if he is okay, but he cannot muster the power to speak.')
    time.sleep(delay)
    print('He grunts towards you desperately, uttering a very hollow:')
    print('')
    time.sleep(delay)
    print('"...Thank"')
    time.sleep(delay)
    print('"You...')

    print('')
    time.sleep(delay)
    input('Continue < ')
    print('')

    time.sleep(delay)
    print('You nod to him silently, reaching out for picking up his near-lifeless body and throwing him over your shoulder.')
    time.sleep(delay)
    print('With Ralph secured on your back, you begin to leave the room of Damazo.')
    time.sleep(delay)
    print('You exit through the door you had entered, and slowly traverse through each room you had encountered.')
    print('')
    time.sleep(delay)
    print('With each trial placed before you, you had suceeded. Resulting in the safe rescue of your friend.')
    time.sleep(delay)
    print('You can see the corpses of the enemies you had slain...')
    time.sleep(delay)
    print('...You remember each riddle you had to solve.')
    time.sleep(delay)
    print('')
    print('You are glad to leave this forsaken place...')
    
    print('')
    time.sleep(delay)
    input('Continue < ')
    print('')

    time.sleep(delay)
    print('After what seems like an eternity carrying Ralph, you find yourself at the foot of the entrance you previously had entered.')
    time.sleep(delay)
    print('You take a sigh of relief, and press on down the steps to where your very hungry steed awaits you.')
    time.sleep(delay)
    print('You realise you had been in the tower the whole day! It is now nightfall.')
    time.sleep(delay)
    print('The surrounding forests cover the landscape near you, the pale moon shining atop the leaves.')
    print('')
    time.sleep(delay)
    print('It reminds you too soon of the pearl riddle...')
    print('')
    time.sleep(delay)
    print('You attach Ralph comfortably to your horse prior to jumping on yourself.')
    time.sleep(delay)
    print('You begin to ride through the night...')

    print('')
    time.sleep(delay)
    input('Continue < ')
    print('')
    
    time.sleep(delay)
    print('You ride through the deafening darkness, unsure if anything is trailing you.')
    time.sleep(delay)
    print('Before the sunrise, you begin to see the light of torches popping up... and up...')
    time.sleep(delay)
    print('Nevaros! You are so close to being returned!')

    print('')
    time.sleep(delay)
    input('Continue < ')
    print('')

    time.sleep(delay)
    print('The tired gallop of your steed becomes a sprint! You charge full speed towards the gates of the kingdom.')
    time.sleep(delay)
    print('You practically burst through the main gates, and are met with the deafening cheers of the townsfolk of Nevaros.')
    print('')
    time.sleep(delay)
    print('Despite the late hour, the people are all here to celebrate your victory.')
    time.sleep(delay)
    print('The guards stationed upon the outer wall must have spotted you riding and called the town to alert.')
    print('')
    time.sleep(delay)
    print('You maneuver your horse to halt, skidding across the cobbled street.')
    time.sleep(delay)
    print('You dismount valiantly, taking Ralph down from the horse. He looks a bit travel-sick.')
    time.sleep(delay)
    print('Instead of taking in the praise, you carry him to the nearest medic. Placing him down, then setting forth to the Kings Keep.')

    print('')
    time.sleep(delay)
    input('Continue < ')
    print('')

    time.sleep(delay)
    print('You arrive in the Kings Keep, the king in his nightgown.')
    time.sleep(delay)
    print(f'"Welcome back Knight {name}! You have done well in your perilous quest."')
    time.sleep(delay)
    print('"There is no way to thank you properly in my lifetime, but please, take this gold and the stretch of land outside my castle."')
    time.sleep(delay)
    print(f'"You once again have done the impossible for Nevaros, {name}."')
    print('')
    time.sleep(delay)
    print('He pats you on the back, before reaching behind him.')
    time.sleep(delay)
    print('"This is yours." He turns to you, bringing forth a chest containing 10,000 gold!')
    time.sleep(delay)
    print('You accept his gift, bowing to the King before heading back out to the streets of cheer below!')
    time.sleep(delay)
    print('Something tells you there is still foul magic at play. You dismiss the thought, ready to take on future challenges...')

    print('')
    time.sleep(delay)
    input('Continue < ')
    print('')

    time.sleep(delay)
    print(f'Thank you for playing "THE TOWER: A Text-Based RPG.", {name}"')
    time.sleep(delay)
    print('I hope you have enjoyed my first game.')
    
    print('')
    time.sleep(delay)
    print('Would you like to play again? Yes or No?')
    print('')

    time.sleep(delay)
    decision = input( '< ')
    if decision.lower() == "yes":
        print('')
        time.sleep(delay)
        print('That is fantastic! Enjoy your next play through!')
        print('')
        time.sleep(delay)
        print('Booting up... "THE TOWER: A Text-Based RPG!"')
        print('')
        print('')
        print('')
        print('')
        print('')
        towergame()
    elif decision.lower() == "no":
        print('')
        time.sleep(delay)
        print('Thank you for playing. Farewell!')
    else:
        print('')
        time.sleep(delay)
        print('Thank you for playing. Farewell!')

towergame()

# print('')
# input( 'Continue < ')
# print('')
